/**
 * @providesModule Images
 */

const images = {
  logo: require('@assets/images/logo.png'),
  phone: require('@assets/images/phone.png'),
  logoSmall: require('@assets/images/logoSmall.png'),
  background: require('@assets/images/background.png'),
  backgroundWhite: require('@assets/images/backgroundWhite.png'),
  logoSmallBlack: require('@assets/images/logoSmallBlack.png'),
  logoSmallWhite: require('@assets/images/logoSmallWhite.png'),
  logoQarabag: require('@assets/images/logoQarabag.png'),
  pdf: require('@assets/images/pdf.png'),
  chevronRight: require('@assets/images/chevron_right.png'),
  checkmark: require('@assets/images/checkmark.png'),
  slider: require('@assets/images/slider.png'),
  contracts: require('@assets/images/contracts.png'),
  products: require('@assets/images/products.png'),
  productsAlternative: require('@assets/images/products_alternative.png'),
  onlinePayment: require('@assets/images/online_payment.png'),
  restart: require("@assets/images/restart.png"),
  backspace: require("@assets/images/backspace.png"),
  touchId: require("@assets/images/touchid.png"),
  pinBackground: require("@assets/images/pinBackground.png"),
  newPinBackground: require("@assets/images/newPinBackground.png"),
  pinBackgroundSecond: require("@assets/images/pinBackground2.png"),
  newBackground: require("@assets/images/newBackground.png"),
  asanimza: require("@assets/images/asanimza.png"),
  finid: require("@assets/images/finid.png"),
  capital: require("@assets/images/capital.png"),
  cancer: require("@assets/images/cancer.png"),
  credit: require("@assets/images/credit.png"),
  doctor: require("@assets/images/doctor.png"),
  future: require("@assets/images/future.png"),
  health: require("@assets/images/health.png"),
  heart: require("@assets/images/heart.png"),
  check: require("@assets/images/check.png"),
  trust: require("@assets/images/trust.png"),
  help: require("@assets/images/help.png"),
  protect: require("@assets/images/protect.png"),
  work: require("@assets/images/work.png"),
  workflow: require("@assets/images/workflow.png"),
  debt: require("@assets/images/debt.png"),
  documents: require("@assets/images/documents.png"),
  amount: require("@assets/images/amount.png"),
  wallet: require("@assets/images/wallet.png"),
  chevronDown: require("@assets/images/chevron_down.png"),
  chevronUp: require("@assets/images/chevron_up.png"),
  chevronUpWhite: require("@assets/images/chevron_up_white.png"),
  chevronDownWhite: require("@assets/images/chevron_down_white.png"),
  marker: require("@assets/images/marker.png"),
  marker2: require("@assets/images/marker2.png"),
  call: require("@assets/images/call.png"),
  gps: require("@assets/images/gps.png"),
  email: require("@assets/images/email.png"),
  info: require("@assets/images/info.png"),
  calculator: require("@assets/images/calculator.png"),
  send: require("@assets/images/send.png"),
  share: require("@assets/images/share.png"),
  socialFacebook: require("@assets/images/socialFacebook.png"),
  socialWhatsapp: require("@assets/images/socialWhatsapp.png"),
  socialInstagram: require("@assets/images/socialInstagram.png"),
  socialYoutube: require("@assets/images/socialYoutube.png"),
  socialLinkedin: require("@assets/images/socialLinkedin.png"),
  search: require("@assets/images/search.png"),
  payment: require("@assets/images/payment.png"),
  backIcon: require("react-navigation-stack/lib/commonjs/vendor/views/assets/back-icon.png")

};

export default images;
